apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache-redirector
  name: cache-redirector-chicago
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache-redirector
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: osg.chic.nrp.internet2.edu
      initContainers:
      - name: chowndata
        image: busybox
      containers:
      - name: stashcache-redirector
        image: efajardo/cache-redirector
        resources:
           limits:
              memory: 8Gi
           requests:
              memory: 4Gi
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: SITENAME
          value: Chicago-Kubernetes-PRP
        - name: XRPORT
          value: "8000"
        - name: REDIRECTOR
          value: osg.chic.nrp.internet2.edu
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/xrootd
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
      volumes:
      - name: config
        configMap:
          name: stashcache-redirector
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File



