apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache-redirector
  name: cache-redirector-greatplains
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache-redirector
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: osg.kans.nrp.internet2.edu
      initContainers:
      - name: chowndata
        image: busybox
      containers:
      - name: stashcache-redirector
        image: efajardo/cache-redirector
        resources:
           limits:
              memory: 8Gi
           requests:
              memory: 4Gi
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: SITENAME
          value: GreatPLains-Kubernetes-PRP
        - name: XRPORT
          value: "8000"
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/xrootd
      volumes:
      - name: config
        configMap:
          name: stashcache-redirector


